// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-events.ts
var list_events_default = defineTool({
  name: "list_events",
  title: "List events",
  description: "List the events the signed-in organizer can access, with date, status, location and registration link slug.",
  inputSchema: {
    status: z.enum(["draft", "published", "cancelled", "completed"]).optional().describe("Only return events with this status."),
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum events to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("events").select(
      "id, name, slug, status, event_date, event_end_date, timezone, location_type, location_value, capacity, registration_limit, ticket_price"
    ).order("event_date", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-event.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_event_default = defineTool2({
  name: "get_event",
  title: "Get event details",
  description: "Get one event the signed-in organizer can access, by event id or registration page slug, including a registration count.",
  inputSchema: {
    event_id: z2.string().uuid().optional().describe("Event id."),
    slug: z2.string().trim().min(1).optional().describe("Registration page slug, used when no event id is given.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id, slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!event_id && !slug) {
      return { content: [{ type: "text", text: "Provide either event_id or slug." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("events").select("*").limit(1);
    query = event_id ? query.eq("id", event_id) : query.eq("slug", slug);
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Event not found or not accessible." }], isError: true };
    const { count } = await supabase.from("registrations").select("id", { count: "exact", head: true }).eq("event_id", data.id);
    const event = { ...data, registration_count: count ?? 0 };
    return {
      content: [{ type: "text", text: JSON.stringify(event, null, 2) }],
      structuredContent: { event }
    };
  }
});

// src/lib/mcp/tools/list-registrations.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_registrations_default = defineTool3({
  name: "list_registrations",
  title: "List event registrations",
  description: "List registrations (attendees) for an event the signed-in organizer can access, including status, VIP flag and check-in time.",
  inputSchema: {
    event_id: z3.string().uuid().describe("Event id to list registrations for."),
    status: z3.enum(["confirmed", "pending", "waitlisted", "cancelled"]).optional().describe("Only return registrations with this status."),
    checked_in: z3.boolean().optional().describe("Filter by whether the attendee has checked in."),
    limit: z3.number().int().min(1).max(200).default(50).describe("Maximum registrations to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id, status, checked_in, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("registrations").select("id, event_id, status, is_vip, notes, checked_in_at, created_at, data").eq("event_id", event_id).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    if (checked_in === true) query = query.not("checked_in_at", "is", null);
    if (checked_in === false) query = query.is("checked_in_at", null);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { registrations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/check-in-attendee.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var check_in_attendee_default = defineTool4({
  name: "check_in_attendee",
  title: "Check in attendee",
  description: "Check in an attendee at an event by registration id. Marks the registration as checked in.",
  inputSchema: {
    registration_id: z4.string().uuid().describe("Registration id of the attendee to check in.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, destructiveHint: false, openWorldHint: false },
  handler: async ({ registration_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("check_in_attendee", { p_registration_id: registration_id });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { result: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yrjeoptsmcemtcreshzy";
var mcp_default = defineMcp({
  name: "remix-of-event-registration-page-template",
  title: "Remix of Event Registration Page Template",
  version: "0.1.0",
  instructions: "Tools for the event view registration platform. Use `list_events` to find the signed-in organizer's events, `get_event` for full details of one event, `list_registrations` to see attendees, and `check_in_attendee` to check someone in at the door.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_events_default, get_event_default, list_registrations_default, check_in_attendee_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
